### PR TITLE
Remove .idea directory

### PR DESCRIPTION
**Pull request by zitnik**
Remove .idea directory used by IntelliJ IDE (RubyMine).

### CODE REVIEW

**Review by agrare — APPROVED** [review]

**Comment by kbrock** [comment]
Remind developers to keep a backup of this directory until all branches have this change merged in.
If they git checkout a branch without this change and then back to master, it will clear out their `.idea` directory in confusing ways.

**Review by kbrock — APPROVED** [review]

**Comment by Fryguy** [comment]
This feels like a personal ignore as opposed to a project ignore.  As such, our general policy on personal ignores (for things like IDEs, OS files, etc) is that you can use git's global gitignore feature.

See https://git-scm.com/docs/gitignore:
> Patterns which a user wants Git to ignore in all situations (e.g., backup or temporary files generated by the user’s editor of choice) generally go into a file specified by core.excludesFile in the user’s ~/.gitconfig. Its default value is $XDG_CONFIG_HOME/git/ignore. If $XDG_CONFIG_HOME is either not set or empty, $HOME/.config/git/ignore is used instead.

**Comment by agrare** [comment]
> This feels like a personal ignore as opposed to a project ignore

While I agree with that we also have `.idea` in the core .gitignore repo (https://github.com/ManageIQ/manageiq/blob/master/.gitignore#L10) and many other of our plugins.

**Comment by Fryguy** [comment]
yeah we shouldn't, IMO...I had expressed in the past those should be removed there as well (and in ui classic where there's a lot of that)

**Pull request merged**
