### PR TITLE
[NAJDORF] Remove merges related to physical_server_profiles

### PR DESCRIPTION
**Pull request by agrare**
Physical Server Profiles were added to core in master/oparin and required a schema change which cannot be backported to najdorf.

This reverts any merges related to physical_server_profiles from the najdorf branch:
* https://github.com/ManageIQ/manageiq-providers-cisco_intersight/pull/42
* https://github.com/ManageIQ/manageiq-providers-cisco_intersight/pull/51
* https://github.com/ManageIQ/manageiq-providers-cisco_intersight/pull/56
* https://github.com/ManageIQ/manageiq-providers-cisco_intersight/pull/58
* https://github.com/ManageIQ/manageiq-providers-cisco_intersight/pull/60

### CODE REVIEW

**Comment by agrare** [comment]
cc @Fryguy

**Comment by Fryguy** [comment]
Why is the fix yarn one being reverted?

**Comment by agrare** [comment]
Because https://github.com/ManageIQ/manageiq-providers-cisco_intersight/pull/51 was the only javascript and keeping it was causing conflicts.

Is that still needed if we don't have any toolbar helpers or js code in the repo?

**Comment by Fryguy** [comment]
Oh I see...the entirety of package.json and yarn.lock will be gone.  This is fine.

**Pull request merged**
